from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication, QMessageBox
import sqlite3
import sys
import os

try:
    db = sqlite3.connect(os.getcwd()+'/База данных/library.db')
    cursor = db.cursor()
except:
    sys.exit()

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 500)
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Dialog.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("border-color: #000000;\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_5 = QtWidgets.QFrame(self.tab)
        self.frame_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(102, 125, 182, 255),stop:0.3  rgba(0, 130, 200, 255),stop:0.6 rgba(0, 130, 200, 255) , stop:1 rgba(102, 125, 182, 255));\n"
"\n"
"border-radius: 30;\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setMaximumSize(QtCore.QSize(592, 257))
        self.frame_6.setStyleSheet("background-color: #f0f0f0;\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Corbel Light")
        font.setPointSize(60)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_12.addWidget(self.label_5)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Corbel Light")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_11.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Corbel Light")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7)
        self.label_21 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Corbel Light")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_11.addWidget(self.label_21)
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Corbel Light")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.gridLayout.addWidget(self.frame_6, 0, 0, 1, 1)
        self.verticalLayout_13.addWidget(self.frame_5)
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setMaximumSize(QtCore.QSize(300, 25))
        font = QtGui.QFont()
        font.setFamily("Corbel Light")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_13.addWidget(self.label_22)
        self.tabWidget.addTab(self.tab, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.iss_table = QtWidgets.QTableWidget(self.tab_1)
        self.iss_table.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.iss_table.setFont(font)
        self.iss_table.setStyleSheet("background-color: rgb(208, 204, 227);")
        self.iss_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.iss_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.iss_table.setLineWidth(5)
        self.iss_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.iss_table.setTabKeyNavigation(True)
        self.iss_table.setObjectName("iss_table")
        self.iss_table.setColumnCount(3)
        self.iss_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        item.setFont(font)
        self.iss_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        item.setFont(font)
        self.iss_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        item.setFont(font)
        self.iss_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout_34.addWidget(self.iss_table)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_17 = QtWidgets.QFrame(self.tab_1)
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_8.addWidget(self.frame_17)
        self.iss_table_ref = QtWidgets.QPushButton(self.tab_1)
        self.iss_table_ref.setMinimumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.iss_table_ref.setFont(font)
        self.iss_table_ref.setStyleSheet("QPushButton\n"
"{        \n"
"    border:3 solid rgb(84, 104, 214);\n"
"    border-radius:15;\n"
"    color:  rgb(84, 104, 214);    \n"
"\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border:3 solid  rgb(84, 104, 214);\n"
"    border-radius:15;\n"
"    color: white;        \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(69, 104, 220, 255), stop:1 rgba(176, 106, 179, 255));;\n"
"}")
        self.iss_table_ref.setObjectName("iss_table_ref")
        self.horizontalLayout_8.addWidget(self.iss_table_ref)
        self.label_17 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_8.addWidget(self.label_17)
        self.verticalLayout_34.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4.addLayout(self.verticalLayout_34)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_18 = QtWidgets.QFrame(self.tab_1)
        self.frame_18.setMaximumSize(QtCore.QSize(189, 185))
        self.frame_18.setStyleSheet("")
        self.frame_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_18 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_37.addWidget(self.label_18)
        self.iss_add1 = QtWidgets.QLineEdit(self.frame_18)
        self.iss_add1.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.iss_add1.setFont(font)
        self.iss_add1.setStyleSheet("background-color: rgb(217, 212, 236);\n"
"border:0;")
        self.iss_add1.setObjectName("iss_add1")
        self.verticalLayout_37.addWidget(self.iss_add1)
        self.iss_add2 = QtWidgets.QLineEdit(self.frame_18)
        self.iss_add2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.iss_add2.setFont(font)
        self.iss_add2.setStyleSheet("background-color: rgb(217, 212, 236);\n"
"border:0;")
        self.iss_add2.setObjectName("iss_add2")
        self.verticalLayout_37.addWidget(self.iss_add2)
        self.iss_add_ok = QtWidgets.QPushButton(self.frame_18)
        self.iss_add_ok.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.iss_add_ok.setFont(font)
        self.iss_add_ok.setStyleSheet("QPushButton\n"
"{        \n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);        \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(69, 104, 220, 255), stop:1 rgba(176, 106, 179, 255));\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);            \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(30, 68, 170, 255), stop:1 rgba(120, 70, 120, 255));\n"
"}")
        self.iss_add_ok.setObjectName("iss_add_ok")
        self.verticalLayout_37.addWidget(self.iss_add_ok)
        self.verticalLayout_36.addLayout(self.verticalLayout_37)
        self.verticalLayout_10.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.tab_1)
        self.frame_19.setMaximumSize(QtCore.QSize(189, 113))
        self.frame_19.setStyleSheet("")
        self.frame_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.line_9 = QtWidgets.QFrame(self.frame_19)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_39.addWidget(self.line_9)
        self.label_19 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_39.addWidget(self.label_19)
        self.iss_search = QtWidgets.QLineEdit(self.frame_19)
        self.iss_search.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.iss_search.setFont(font)
        self.iss_search.setStyleSheet("background-color: rgb(217, 212, 236);\n"
"border:0;")
        self.iss_search.setObjectName("iss_search")
        self.verticalLayout_39.addWidget(self.iss_search)
        self.iss_search_ok = QtWidgets.QPushButton(self.frame_19)
        self.iss_search_ok.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.iss_search_ok.setFont(font)
        self.iss_search_ok.setStyleSheet("QPushButton\n"
"{        \n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);        \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(69, 104, 220, 255), stop:1 rgba(176, 106, 179, 255));\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);            \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(30, 68, 170, 255), stop:1 rgba(120, 70, 120, 255));\n"
"}")
        self.iss_search_ok.setObjectName("iss_search_ok")
        self.verticalLayout_39.addWidget(self.iss_search_ok)
        self.verticalLayout_38.addLayout(self.verticalLayout_39)
        self.verticalLayout_10.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.tab_1)
        self.frame_20.setMaximumSize(QtCore.QSize(189, 113))
        self.frame_20.setStyleSheet("")
        self.frame_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.line_10 = QtWidgets.QFrame(self.frame_20)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_41.addWidget(self.line_10)
        self.label_20 = QtWidgets.QLabel(self.frame_20)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 19))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_41.addWidget(self.label_20)
        self.iss_del = QtWidgets.QLineEdit(self.frame_20)
        self.iss_del.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.iss_del.setFont(font)
        self.iss_del.setStyleSheet("background-color: rgb(217, 212, 236);\n"
"border:0;")
        self.iss_del.setObjectName("iss_del")
        self.verticalLayout_41.addWidget(self.iss_del)
        self.iss_del_ok = QtWidgets.QPushButton(self.frame_20)
        self.iss_del_ok.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.iss_del_ok.setFont(font)
        self.iss_del_ok.setStyleSheet("QPushButton\n"
"{        \n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);        \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(69, 104, 220, 255), stop:1 rgba(176, 106, 179, 255));\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);                \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(30, 68, 170, 255), stop:1 rgba(120, 70, 120, 255));\n"
"}")
        self.iss_del_ok.setObjectName("iss_del_ok")
        self.verticalLayout_41.addWidget(self.iss_del_ok)
        self.verticalLayout_40.addLayout(self.verticalLayout_41)
        self.verticalLayout_10.addWidget(self.frame_20)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.read_table = QtWidgets.QTableWidget(self.tab_2)
        self.read_table.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.read_table.setFont(font)
        self.read_table.setStyleSheet("background-color: rgb(212, 216, 180);")
        self.read_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.read_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.read_table.setLineWidth(5)
        self.read_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.read_table.setTabKeyNavigation(True)
        self.read_table.setObjectName("read_table")
        self.read_table.setColumnCount(4)
        self.read_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        item.setFont(font)
        self.read_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        item.setFont(font)
        self.read_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        item.setFont(font)
        self.read_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        item.setFont(font)
        self.read_table.setHorizontalHeaderItem(3, item)
        self.verticalLayout_33.addWidget(self.read_table)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_16 = QtWidgets.QFrame(self.tab_2)
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_7.addWidget(self.frame_16)
        self.read_table_ref = QtWidgets.QPushButton(self.tab_2)
        self.read_table_ref.setMinimumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.read_table_ref.setFont(font)
        self.read_table_ref.setStyleSheet("QPushButton\n"
"{        \n"
"    border:3 solid #84a02b;\n"
"    border-radius:15;\n"
"    color: rgb(122, 147, 40);    \n"
"\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border:3 solid #84a02b;\n"
"    border-radius:15;\n"
"    color: white;        \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(132, 160, 43, 255), stop:1 rgba(183, 198, 86, 255));\n"
"}")
        self.read_table_ref.setObjectName("read_table_ref")
        self.horizontalLayout_7.addWidget(self.read_table_ref)
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.verticalLayout_33.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_33)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.frame_13 = QtWidgets.QFrame(self.tab_2)
        self.frame_13.setMaximumSize(QtCore.QSize(189, 185))
        self.frame_13.setStyleSheet("")
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_13 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_28.addWidget(self.label_13)
        self.read_add1 = QtWidgets.QLineEdit(self.frame_13)
        self.read_add1.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.read_add1.setFont(font)
        self.read_add1.setStyleSheet("background-color: rgb(222, 226, 189);\n"
"border:0;")
        self.read_add1.setObjectName("read_add1")
        self.verticalLayout_28.addWidget(self.read_add1)
        self.read_add2 = QtWidgets.QLineEdit(self.frame_13)
        self.read_add2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.read_add2.setFont(font)
        self.read_add2.setStyleSheet("background-color: rgb(222, 226, 189);\n"
"border:0;")
        self.read_add2.setObjectName("read_add2")
        self.verticalLayout_28.addWidget(self.read_add2)
        self.read_add3 = QtWidgets.QLineEdit(self.frame_13)
        self.read_add3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.read_add3.setFont(font)
        self.read_add3.setStyleSheet("background-color: rgb(222, 226, 189);\n"
"border:0;")
        self.read_add3.setObjectName("read_add3")
        self.verticalLayout_28.addWidget(self.read_add3)
        self.read_add_ok = QtWidgets.QPushButton(self.frame_13)
        self.read_add_ok.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.read_add_ok.setFont(font)
        self.read_add_ok.setStyleSheet("QPushButton\n"
"{        \n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);        \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(132, 160, 43, 255), stop:1 rgba(198, 198, 83, 255));\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);            \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(87, 106, 28, 255), stop:1 rgba(128, 138, 60, 255));\n"
"}")
        self.read_add_ok.setObjectName("read_add_ok")
        self.verticalLayout_28.addWidget(self.read_add_ok)
        self.verticalLayout_27.addLayout(self.verticalLayout_28)
        self.verticalLayout_26.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.tab_2)
        self.frame_14.setMaximumSize(QtCore.QSize(189, 113))
        self.frame_14.setStyleSheet("")
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.line_7 = QtWidgets.QFrame(self.frame_14)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_30.addWidget(self.line_7)
        self.label_14 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_30.addWidget(self.label_14)
        self.read_search = QtWidgets.QLineEdit(self.frame_14)
        self.read_search.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.read_search.setFont(font)
        self.read_search.setStyleSheet("background-color: rgb(222, 226, 189);\n"
"border:0;")
        self.read_search.setObjectName("read_search")
        self.verticalLayout_30.addWidget(self.read_search)
        self.read_search_ok = QtWidgets.QPushButton(self.frame_14)
        self.read_search_ok.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.read_search_ok.setFont(font)
        self.read_search_ok.setStyleSheet("QPushButton\n"
"{        \n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);        \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(132, 160, 43, 255), stop:1 rgba(198, 198, 83, 255));\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);            \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(87, 106, 28, 255), stop:1 rgba(128, 138, 60, 255));\n"
"}")
        self.read_search_ok.setObjectName("read_search_ok")
        self.verticalLayout_30.addWidget(self.read_search_ok)
        self.verticalLayout_29.addLayout(self.verticalLayout_30)
        self.verticalLayout_26.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.tab_2)
        self.frame_15.setMaximumSize(QtCore.QSize(189, 113))
        self.frame_15.setStyleSheet("")
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.line_8 = QtWidgets.QFrame(self.frame_15)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_32.addWidget(self.line_8)
        self.label_15 = QtWidgets.QLabel(self.frame_15)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 19))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_32.addWidget(self.label_15)
        self.read_del = QtWidgets.QLineEdit(self.frame_15)
        self.read_del.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.read_del.setFont(font)
        self.read_del.setStyleSheet("background-color: rgb(222, 226, 189);\n"
"border:0;")
        self.read_del.setObjectName("read_del")
        self.verticalLayout_32.addWidget(self.read_del)
        self.read_del_ok = QtWidgets.QPushButton(self.frame_15)
        self.read_del_ok.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.read_del_ok.setFont(font)
        self.read_del_ok.setStyleSheet("QPushButton\n"
"{        \n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);        \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(132, 160, 43, 255), stop:1 rgba(198, 198, 83, 255));\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);                \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(87, 106, 28, 255), stop:1 rgba(128, 138, 60, 255));\n"
"}")
        self.read_del_ok.setObjectName("read_del_ok")
        self.verticalLayout_32.addWidget(self.read_del_ok)
        self.verticalLayout_31.addLayout(self.verticalLayout_32)
        self.verticalLayout_26.addWidget(self.frame_15)
        self.horizontalLayout_3.addLayout(self.verticalLayout_26)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.book_table = QtWidgets.QTableWidget(self.tab_3)
        self.book_table.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.book_table.setFont(font)
        self.book_table.setStyleSheet("background-color: rgb(239, 206, 183);")
        self.book_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.book_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.book_table.setLineWidth(5)
        self.book_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.book_table.setTabKeyNavigation(True)
        self.book_table.setObjectName("book_table")
        self.book_table.setColumnCount(4)
        self.book_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        item.setFont(font)
        self.book_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        item.setFont(font)
        self.book_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        item.setFont(font)
        self.book_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        item.setFont(font)
        self.book_table.setHorizontalHeaderItem(3, item)
        self.verticalLayout_18.addWidget(self.book_table)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_9 = QtWidgets.QFrame(self.tab_3)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_5.addWidget(self.frame_9)
        self.book_table_ref = QtWidgets.QPushButton(self.tab_3)
        self.book_table_ref.setMinimumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.book_table_ref.setFont(font)
        self.book_table_ref.setStyleSheet("QPushButton\n"
"{        \n"
"    border:3 solid rgb(207, 103, 82);\n"
"    border-radius:15;\n"
"    color: rgb(207, 103, 82);    \n"
"    \n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border:3 solid rgb(207, 103, 82);\n"
"    border-radius:15;\n"
"    color: white;    \n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(226, 113, 90, 255), stop:1 rgba(242, 160, 84, 255));\n"
"}")
        self.book_table_ref.setObjectName("book_table_ref")
        self.horizontalLayout_5.addWidget(self.book_table_ref)
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.verticalLayout_18.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_10 = QtWidgets.QFrame(self.tab_3)
        self.frame_10.setMaximumSize(QtCore.QSize(189, 185))
        self.frame_10.setStyleSheet("")
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_21.addWidget(self.label_10)
        self.book_add1 = QtWidgets.QLineEdit(self.frame_10)
        self.book_add1.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.book_add1.setFont(font)
        self.book_add1.setStyleSheet("background-color: rgb(239, 212, 192);\n"
"border:0;")
        self.book_add1.setObjectName("book_add1")
        self.verticalLayout_21.addWidget(self.book_add1)
        self.book_add2 = QtWidgets.QLineEdit(self.frame_10)
        self.book_add2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.book_add2.setFont(font)
        self.book_add2.setStyleSheet("background-color: rgb(239, 212, 192);\n"
"border:0;")
        self.book_add2.setObjectName("book_add2")
        self.verticalLayout_21.addWidget(self.book_add2)
        self.book_add3 = QtWidgets.QLineEdit(self.frame_10)
        self.book_add3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.book_add3.setFont(font)
        self.book_add3.setStyleSheet("background-color: rgb(239, 212, 192);\n"
"border:0;")
        self.book_add3.setObjectName("book_add3")
        self.verticalLayout_21.addWidget(self.book_add3)
        self.book_add_ok = QtWidgets.QPushButton(self.frame_10)
        self.book_add_ok.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.book_add_ok.setFont(font)
        self.book_add_ok.setStyleSheet("QPushButton\n"
"{        \n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);        \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(226, 113, 90, 255), stop:1 rgba(242, 160, 84, 255));\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);            \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(149, 75, 59, 255), stop:1 rgba(158, 104, 55, 255));\n"
"}")
        self.book_add_ok.setObjectName("book_add_ok")
        self.verticalLayout_21.addWidget(self.book_add_ok)
        self.verticalLayout_20.addLayout(self.verticalLayout_21)
        self.verticalLayout_19.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.tab_3)
        self.frame_11.setMaximumSize(QtCore.QSize(189, 113))
        self.frame_11.setStyleSheet("")
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.line_5 = QtWidgets.QFrame(self.frame_11)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_23.addWidget(self.line_5)
        self.label_11 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_23.addWidget(self.label_11)
        self.book_search = QtWidgets.QLineEdit(self.frame_11)
        self.book_search.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.book_search.setFont(font)
        self.book_search.setStyleSheet("background-color: rgb(239, 212, 192);\n"
"border:0;")
        self.book_search.setObjectName("book_search")
        self.verticalLayout_23.addWidget(self.book_search)
        self.book_search_ok = QtWidgets.QPushButton(self.frame_11)
        self.book_search_ok.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.book_search_ok.setFont(font)
        self.book_search_ok.setStyleSheet("QPushButton\n"
"{        \n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);        \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(226, 113, 90, 255), stop:1 rgba(242, 160, 84, 255));\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);            \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(149, 75, 59, 255), stop:1 rgba(158, 104, 55, 255));\n"
"}")
        self.book_search_ok.setObjectName("book_search_ok")
        self.verticalLayout_23.addWidget(self.book_search_ok)
        self.verticalLayout_22.addLayout(self.verticalLayout_23)
        self.verticalLayout_19.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.tab_3)
        self.frame_12.setMaximumSize(QtCore.QSize(189, 113))
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.line_6 = QtWidgets.QFrame(self.frame_12)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_25.addWidget(self.line_6)
        self.label_12 = QtWidgets.QLabel(self.frame_12)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 19))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_25.addWidget(self.label_12)
        self.book_del = QtWidgets.QLineEdit(self.frame_12)
        self.book_del.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.book_del.setFont(font)
        self.book_del.setStyleSheet("background-color: rgb(239, 212, 192);\n"
"border:0;")
        self.book_del.setObjectName("book_del")
        self.verticalLayout_25.addWidget(self.book_del)
        self.book_del_ok = QtWidgets.QPushButton(self.frame_12)
        self.book_del_ok.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.book_del_ok.setFont(font)
        self.book_del_ok.setStyleSheet("QPushButton\n"
"{        \n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);        \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(226, 113, 90, 255), stop:1 rgba(242, 160, 84, 255));\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);            \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(149, 75, 59, 255), stop:1 rgba(158, 104, 55, 255));\n"
"}")
        self.book_del_ok.setObjectName("book_del_ok")
        self.verticalLayout_25.addWidget(self.book_del_ok)
        self.verticalLayout_24.addLayout(self.verticalLayout_25)
        self.verticalLayout_19.addWidget(self.frame_12)
        self.horizontalLayout_6.addLayout(self.verticalLayout_19)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.auth_table = QtWidgets.QTableWidget(self.tab_4)
        self.auth_table.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.auth_table.setFont(font)
        self.auth_table.setStyleSheet("background-color: rgb(170, 191, 214);")
        self.auth_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.auth_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.auth_table.setLineWidth(5)
        self.auth_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.auth_table.setTabKeyNavigation(True)
        self.auth_table.setObjectName("auth_table")
        self.auth_table.setColumnCount(4)
        self.auth_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        item.setFont(font)
        self.auth_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        item.setFont(font)
        self.auth_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        item.setFont(font)
        self.auth_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        item.setFont(font)
        self.auth_table.setHorizontalHeaderItem(3, item)
        self.verticalLayout_9.addWidget(self.auth_table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.tab_4)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout.addWidget(self.frame_4)
        self.auth_table_ref = QtWidgets.QPushButton(self.tab_4)
        self.auth_table_ref.setMinimumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.auth_table_ref.setFont(font)
        self.auth_table_ref.setStyleSheet("QPushButton\n"
"{        \n"
"    border:3 solid rgb(59, 139, 235);\n"
"    border-radius:15;\n"
"    color: rgb(59, 139, 235);\n"
"\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border:3 solid rgb(59, 139, 235);\n"
"    border-radius:15;\n"
"    color: white;\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(144, 185, 235, 255), stop:1 rgba(210, 169, 202, 255));\n"
"}")
        self.auth_table_ref.setObjectName("auth_table_ref")
        self.horizontalLayout.addWidget(self.auth_table_ref)
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame = QtWidgets.QFrame(self.tab_4)
        self.frame.setMaximumSize(QtCore.QSize(189, 185))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.auth_add1 = QtWidgets.QLineEdit(self.frame)
        self.auth_add1.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.auth_add1.setFont(font)
        self.auth_add1.setStyleSheet("background-color: rgb(196, 219, 246);\n"
"border:0;")
        self.auth_add1.setObjectName("auth_add1")
        self.verticalLayout_2.addWidget(self.auth_add1)
        self.auth_add2 = QtWidgets.QLineEdit(self.frame)
        self.auth_add2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.auth_add2.setFont(font)
        self.auth_add2.setStyleSheet("background-color: rgb(196, 219, 246);\n"
"border:0;")
        self.auth_add2.setObjectName("auth_add2")
        self.verticalLayout_2.addWidget(self.auth_add2)
        self.auth_add3 = QtWidgets.QLineEdit(self.frame)
        self.auth_add3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.auth_add3.setFont(font)
        self.auth_add3.setStyleSheet("background-color: rgb(196, 219, 246);\n"
"border:0;")
        self.auth_add3.setObjectName("auth_add3")
        self.verticalLayout_2.addWidget(self.auth_add3)
        self.auth_add_ok = QtWidgets.QPushButton(self.frame)
        self.auth_add_ok.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.auth_add_ok.setFont(font)
        self.auth_add_ok.setStyleSheet("QPushButton\n"
"{        \n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);        \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(59, 139, 235, 255), stop:1 rgba(209, 123, 193, 255));\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);            \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(40, 93, 158, 255), stop:1 rgba(162, 95, 150, 255));\n"
"}")
        self.auth_add_ok.setObjectName("auth_add_ok")
        self.verticalLayout_2.addWidget(self.auth_add_ok)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.tab_4)
        self.frame_3.setMaximumSize(QtCore.QSize(189, 113))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.line_2 = QtWidgets.QFrame(self.frame_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.auth_search = QtWidgets.QLineEdit(self.frame_3)
        self.auth_search.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.auth_search.setFont(font)
        self.auth_search.setStyleSheet("background-color: rgb(196, 219, 246);\n"
"border:0;")
        self.auth_search.setObjectName("auth_search")
        self.verticalLayout_4.addWidget(self.auth_search)
        self.auth_search_ok = QtWidgets.QPushButton(self.frame_3)
        self.auth_search_ok.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.auth_search_ok.setFont(font)
        self.auth_search_ok.setStyleSheet("QPushButton\n"
"{        \n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);        \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(59, 139, 235, 255), stop:1 rgba(209, 123, 193, 255));\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);            \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(40, 93, 158, 255), stop:1 rgba(162, 95, 150, 255));\n"
"}")
        self.auth_search_ok.setObjectName("auth_search_ok")
        self.verticalLayout_4.addWidget(self.auth_search_ok)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.tab_4)
        self.frame_2.setMaximumSize(QtCore.QSize(189, 113))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 19))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.auth_del = QtWidgets.QLineEdit(self.frame_2)
        self.auth_del.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.auth_del.setFont(font)
        self.auth_del.setStyleSheet("background-color: rgb(196, 219, 246);\n"
"border:0;")
        self.auth_del.setObjectName("auth_del")
        self.verticalLayout_3.addWidget(self.auth_del)
        self.auth_del_ok = QtWidgets.QPushButton(self.frame_2)
        self.auth_del_ok.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.auth_del_ok.setFont(font)
        self.auth_del_ok.setStyleSheet("QPushButton\n"
"{        \n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);        \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(59, 139, 235, 255), stop:1 rgba(209, 123, 193, 255));\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-radius:15;\n"
"    color: rgb(255, 255, 255);            \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(40, 93, 158, 255), stop:1 rgba(162, 95, 150, 255));\n"
"}")
        self.auth_del_ok.setObjectName("auth_del_ok")
        self.verticalLayout_3.addWidget(self.auth_del_ok)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.iss_table.horizontalHeader().setStyleSheet("background-color: #f0f0f0")
        self.read_table.horizontalHeader().setStyleSheet("background-color: #f0f0f0")
        self.book_table.horizontalHeader().setStyleSheet("background-color: #f0f0f0")
        self.auth_table.horizontalHeader().setStyleSheet("background-color: #f0f0f0")

        self.auth_add1.setPlaceholderText("Имя")
        self.auth_add2.setPlaceholderText("Фамилия")
        self.auth_add3.setPlaceholderText("Страна")
        self.auth_search.setPlaceholderText("Имя/Фамилия/Страна")
        self.auth_del.setPlaceholderText("ID автора")
        
        self.book_add1.setPlaceholderText("Название")
        self.book_add2.setPlaceholderText("ID автора")
        self.book_add3.setPlaceholderText("Год написания")
        self.book_search.setPlaceholderText("Название/ID автора/Год")
        self.book_del.setPlaceholderText("ID книги")

        self.read_add1.setPlaceholderText("Имя")
        self.read_add2.setPlaceholderText("Фамилия")
        self.read_add3.setPlaceholderText("E-mail")
        self.read_search.setPlaceholderText("Имя/Фамилия")
        self.read_del.setPlaceholderText("ID читателя")

        self.iss_add1.setPlaceholderText("ID читателя")
        self.iss_add2.setPlaceholderText("ID книги")
        self.iss_search.setPlaceholderText("ID читателя/ID книги")
        self.iss_del.setPlaceholderText("ID выдачи")

        self.auth_add_ok.clicked.connect(self.f_auth_add_ok)
        self.auth_search_ok.clicked.connect(self.f_auth_search_ok)
        self.auth_del_ok.clicked.connect(self.f_auth_del_ok)
        self.auth_table_ref.clicked.connect(self.f_auth_table_ref)

        self.book_add_ok.clicked.connect(self.f_book_add_ok)
        self.book_search_ok.clicked.connect(self.f_book_search_ok)
        self.book_del_ok.clicked.connect(self.f_book_del_ok)
        self.book_table_ref.clicked.connect(self.f_book_table_ref)

        self.read_add_ok.clicked.connect(self.f_read_add_ok)
        self.read_search_ok.clicked.connect(self.f_read_search_ok)
        self.read_del_ok.clicked.connect(self.f_read_del_ok)
        self.read_table_ref.clicked.connect(self.f_read_table_ref)

        self.iss_add_ok.clicked.connect(self.f_iss_add_ok)
        self.iss_search_ok.clicked.connect(self.f_iss_search_ok)
        self.iss_del_ok.clicked.connect(self.f_iss_del_ok)
        self.iss_table_ref.clicked.connect(self.f_iss_table_ref)

    def f_auth_add_ok(self):
        try:         
            cursor.execute('''CREATE TABLE IF NOT EXISTS authors (id_auth integer PRIMARY KEY AUTOINCREMENT, 
                name VARCHAR(50), lastname VARCHAR(50), country VARCHAR(50))''')
            db.commit()
            data = ((self.auth_add1.text()).lower(), (self.auth_add2.text()).lower(), (self.auth_add3.text().lower()))
            if (len(data[0])==0 or len(data[1])==0 or len(data[2])==0):
                msg=QMessageBox()
                msg.setText('Заполните ВСЕ поля!')
                msg.setWindowTitle(' ')
                msg.exec_()
            else:
                cursor.execute('''INSERT INTO authors (name, lastname, country) VALUES (?,?,?)''', data)        
                db.commit()
                msg=QMessageBox()
                msg.setText('Автор добавлен!')
                msg.setWindowTitle(' ')
                msg.exec_()

        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("sqlite3")
            msg.setInformativeText('Ошибка при работе с базой данных!')
            msg.setWindowTitle("Ошибка")
            msg.exec_()
    def f_auth_search_ok(self):
        try:           
            text = self.auth_search.text().lower()
            cursor.execute('''SELECT * FROM authors WHERE name = ? OR lastname = ? OR country = ? ORDER BY name''',(text,text,text))
            data = cursor.fetchall()
            db.commit()
            if (len(data)==0):
                msg=QMessageBox()
                msg.setText('Запись НЕ найдена!')
                msg.setWindowTitle(' ')
                msg.exec_()
            else:
                row = len(data)
                column = len(data[0])
                self.auth_table.setRowCount(row)
                for i in range(row):
                    for j in range(column):
                        item = QtWidgets.QTableWidgetItem(str(data[i][j]))
                        self.auth_table.setItem(i,j,item)                
                self.label_4.setText("Всего записей: " + str(row))
        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("sqlite3")
            msg.setInformativeText('Ошибка при работе с базой данных!')
            msg.setWindowTitle("Ошибка")
            msg.exec_()         
    def f_auth_del_ok(self):
        try:           
            text = self.auth_del.text()
            data = cursor.execute('''SELECT * FROM authors WHERE id_auth = ?''',(text,))
            db.commit()
            if (data.fetchone() is None):
                msg=QMessageBox()
                msg.setText('Запись НЕ найдена!')
                msg.setWindowTitle(' ')
                msg.exec_()
            else:
                cursor.execute('''DELETE FROM authors WHERE id_auth = ?''',(text,))
                db.commit()
                msg=QMessageBox()
                msg.setText('Автор удален!')
                msg.setWindowTitle(' ')
                msg.exec_()   
        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("sqlite3")
            msg.setInformativeText('Ошибка при работе с базой данных!')
            msg.setWindowTitle("Ошибка")
            msg.exec_()      
    def f_auth_table_ref(self):
        try:
            cursor.execute('''SELECT * FROM authors ORDER BY name''')
            data = cursor.fetchall()
            db.commit()
            if (len(data)!=0):    
                row = len(data)
                column = len(data[0])
                self.auth_table.setRowCount(row)
                for i in range(row):
                    for j in range(column):
                        item = QtWidgets.QTableWidgetItem(str(data[i][j]))
                        self.auth_table.setItem(i,j,item)                
                self.label_4.setText("Всего записей: " + str(row))
            else:
                self.auth_table.setRowCount(0)
                self.label_4.setText("Всего записей: 0")

        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("sqlite3")
            msg.setInformativeText('Ошибка при работе с базой данных!')
            msg.setWindowTitle("Ошибка")
            msg.exec_()
        
    def f_book_add_ok(self):
        try:         
            cursor.execute('''CREATE TABLE IF NOT EXISTS books (id_book integer PRIMARY KEY AUTOINCREMENT, 
                name VARCHAR(100), author_id integer, year VARCHAR(20), FOREIGN KEY(author_id) REFERENCES authors(id_auth))''')
            db.commit()
            data = ((self.book_add1.text()).lower(), (self.book_add2.text()).lower(), (self.book_add3.text().lower()))
            cursor.execute('''SELECT * FROM authors WHERE id_auth = ?''',(data[1],))
            data_auth = cursor.fetchall()
            db.commit()

            if (len(data[0])==0 or len(data[1])==0 or len(data[2])==0):
                msg=QMessageBox()
                msg.setText('Заполните ВСЕ поля!')
                msg.setWindowTitle(' ')
                msg.exec_()
            elif (len(data_auth)==0):
                msg=QMessageBox()
                msg.setText('Автор НЕ найден!')
                msg.setWindowTitle(' ')
                msg.exec_()
            else:
                cursor.execute('''INSERT INTO books (name, author_id, year) VALUES (?,?,?)''', data)        
                db.commit()
                msg=QMessageBox()
                msg.setText('Книга добавлена!')
                msg.setWindowTitle(' ')
                msg.exec_()

        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("sqlite3")
            msg.setInformativeText('Ошибка при работе с базой данных!')
            msg.setWindowTitle("Ошибка")
            msg.exec_()
    def f_book_search_ok(self):
        try:           
            text = self.book_search.text().lower()
            cursor.execute('''SELECT * FROM books WHERE name = ? OR author_id = ? OR year = ? ORDER BY name''',(text,text,text))
            data = cursor.fetchall()
            db.commit()
            if (len(data)==0):
                msg=QMessageBox()
                msg.setText('Запись НЕ найдена!')
                msg.setWindowTitle(' ')
                msg.exec_()
            else:
                row = len(data)
                column = len(data[0])
                self.book_table.setRowCount(row)
                for i in range(row):
                    for j in range(column):
                        if (j==2):
                            cursor.execute('''SELECT * FROM authors WHERE id_auth = ?''',(data[i][j],))
                            db.commit()
                            data_auth = cursor.fetchall()
                            item = QtWidgets.QTableWidgetItem(data_auth[0][1] + " " + data_auth[0][2])
                            self.book_table.setItem(i,j,item)
                        else:
                            item = QtWidgets.QTableWidgetItem(str(data[i][j]))
                            self.book_table.setItem(i,j,item)                
                self.label_9.setText("Всего записей: " + str(row))
        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("sqlite3")
            msg.setInformativeText('Ошибка при работе с базой данных!')
            msg.setWindowTitle("Ошибка")
            msg.exec_()
    def f_book_del_ok(self):
        try:           
            text = self.book_del.text()
            data = cursor.execute('''SELECT * FROM books WHERE id_book = ?''',(text,))
            db.commit()
            if (data.fetchone() is None):
                msg=QMessageBox()
                msg.setText('Запись НЕ найдена!')
                msg.setWindowTitle(' ')
                msg.exec_()
            else:
                cursor.execute('''DELETE FROM books WHERE id_book = ?''',(text,))
                db.commit()
                msg=QMessageBox()
                msg.setText('Книга удалена!')
                msg.setWindowTitle(' ')
                msg.exec_()   
        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("sqlite3")
            msg.setInformativeText('Ошибка при работе с базой данных!')
            msg.setWindowTitle("Ошибка")
            msg.exec_()
    def f_book_table_ref(self):
        try:
            cursor.execute('''SELECT * FROM books ORDER BY name''')
            data = cursor.fetchall()
            db.commit()
            if (len(data)!=0):    
                row = len(data)
                column = len(data[0])
                self.book_table.setRowCount(row)
                for i in range(row):
                    for j in range(column):
                        if (j==2):
                            cursor.execute('''SELECT * FROM authors WHERE id_auth = ?''',(data[i][j],))
                            db.commit()
                            data_auth = cursor.fetchall()
                            item = QtWidgets.QTableWidgetItem(data_auth[0][1] + " " + data_auth[0][2])
                            self.book_table.setItem(i,j,item)
                        else:
                            item = QtWidgets.QTableWidgetItem(str(data[i][j]))
                            self.book_table.setItem(i,j,item)                
                self.label_9.setText("Всего записей: " + str(row))
            else:
                self.book_table.setRowCount(0)
                self.label_9.setText("Всего записей: 0")

        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("sqlite3")
            msg.setInformativeText('Ошибка при работе с базой данных!')
            msg.setWindowTitle("Ошибка")
            msg.exec_()

    def f_read_add_ok(self):
        try:         
            cursor.execute('''CREATE TABLE IF NOT EXISTS readers (id_read integer PRIMARY KEY AUTOINCREMENT, 
                name VARCHAR(50), lastname VARCHAR(50), email VARCHAR(100))''')
            db.commit()
            data = ((self.read_add1.text()).lower(), (self.read_add2.text()).lower(), (self.read_add3.text().lower()))
            if (len(data[0])==0 or len(data[1])==0 or len(data[2])==0):
                msg=QMessageBox()
                msg.setText('Заполните ВСЕ поля!')
                msg.setWindowTitle(' ')
                msg.exec_()
            elif ("@" not in data[2] or "." not in data[2]):
                msg=QMessageBox()
                msg.setText('Неправильный E-mail!')
                msg.setWindowTitle(' ')
                msg.exec_()
            else:
                cursor.execute('''INSERT INTO readers (name, lastname, email) VALUES (?,?,?)''', data)        
                db.commit()
                msg=QMessageBox()
                msg.setText('Читатель добавлен!')
                msg.setWindowTitle(' ')
                msg.exec_()

        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("sqlite3")
            msg.setInformativeText('Ошибка при работе с базой данных!')
            msg.setWindowTitle("Ошибка")
            msg.exec_()
    def f_read_search_ok(self):
        try:           
            text = self.read_search.text().lower()
            cursor.execute('''SELECT * FROM readers WHERE name = ? OR lastname = ? ORDER BY name''',(text,text))
            data = cursor.fetchall()
            db.commit()
            if (len(data)==0):
                msg=QMessageBox()
                msg.setText('Запись НЕ найдена!')
                msg.setWindowTitle(' ')
                msg.exec_()
            else:
                row = len(data)
                column = len(data[0])
                self.read_table.setRowCount(row)
                for i in range(row):
                    for j in range(column):
                        item = QtWidgets.QTableWidgetItem(str(data[i][j]))
                        self.read_table.setItem(i,j,item)                
                self.label_16.setText("Всего записей: " + str(row))
        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("sqlite3")
            msg.setInformativeText('Ошибка при работе с базой данных!')
            msg.setWindowTitle("Ошибка")
            msg.exec_()
    def f_read_del_ok(self):
        try:           
            text = self.read_del.text()
            data = cursor.execute('''SELECT * FROM readers WHERE id_read = ?''',(text,))
            db.commit()
            if (data.fetchone() is None):
                msg=QMessageBox()
                msg.setText('Запись НЕ найдена!')
                msg.setWindowTitle(' ')
                msg.exec_()
            else:
                cursor.execute('''DELETE FROM readers WHERE id_read = ?''',(text,))
                db.commit()
                msg=QMessageBox()
                msg.setText('Читатель удален!')
                msg.setWindowTitle(' ')
                msg.exec_()   
        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("sqlite3")
            msg.setInformativeText('Ошибка при работе с базой данных!')
            msg.setWindowTitle("Ошибка")
            msg.exec_()   
    def f_read_table_ref(self):
        try:
            cursor.execute('''SELECT * FROM readers ORDER BY name''')
            data = cursor.fetchall()
            db.commit()
            if (len(data)!=0):    
                row = len(data)
                column = len(data[0])
                self.read_table.setRowCount(row)
                for i in range(row):
                    for j in range(column):
                        item = QtWidgets.QTableWidgetItem(str(data[i][j]))
                        self.read_table.setItem(i,j,item)                
                self.label_16.setText("Всего записей: " + str(row))
            else:
                self.read_table.setRowCount(0)
                self.label_16.setText("Всего записей: 0")

        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("sqlite3")
            msg.setInformativeText('Ошибка при работе с базой данных!')
            msg.setWindowTitle("Ошибка")
            msg.exec_()

    def f_iss_add_ok(self):
        try:         
            cursor.execute('''CREATE TABLE IF NOT EXISTS issued (id_iss integer PRIMARY KEY AUTOINCREMENT, 
                read_id VARCHAR(50), book_id VARCHAR(50))''')
            db.commit()
            data = ((self.iss_add1.text()).lower(), (self.iss_add2.text()).lower())
            cursor.execute('''SELECT * FROM readers WHERE id_read = ?''',(data[0],))
            data_read = cursor.fetchall()
            db.commit()
            cursor.execute('''SELECT * FROM books WHERE id_book = ?''', (data[1],))
            data_book = cursor.fetchall()
            db.commit()

            if (len(data[0])==0 or len(data[1])==0):
                msg=QMessageBox()
                msg.setText('Заполните ВСЕ поля!')
                msg.setWindowTitle(' ')
                msg.exec_()
            elif (len(data_read)==0):
                msg=QMessageBox()
                msg.setText('Читатель НЕ найден!')
                msg.setWindowTitle(' ')
                msg.exec_()
            elif(len(data_book)==0):
                msg=QMessageBox()
                msg.setText('Книга НЕ найдена!')
                msg.setWindowTitle(' ')
                msg.exec_()
            else:
                cursor.execute('''INSERT INTO issued (read_id, book_id) VALUES (?,?)''', data)        
                db.commit()
                msg=QMessageBox()
                msg.setText('Выдача сохранена!')
                msg.setWindowTitle(' ')
                msg.exec_()

        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("sqlite3")
            msg.setInformativeText('Ошибка при работе с базой данных!')
            msg.setWindowTitle("Ошибка")
            msg.exec_()
    def f_iss_search_ok(self):
        try:           
            text = self.iss_search.text().lower()
            cursor.execute('''SELECT * FROM issued WHERE read_id = ? OR book_id = ?''',(text,text))
            data = cursor.fetchall()
            db.commit()
            if (len(data)==0):
                msg=QMessageBox()
                msg.setText('Запись НЕ найдена!')
                msg.setWindowTitle(' ')
                msg.exec_()
            else:
                row = len(data)
                column = len(data[0])
                self.iss_table.setRowCount(row)
                for i in range(row):
                    for j in range(column):
                        if (j==1):
                            cursor.execute('''SELECT * FROM readers WHERE id_read = ?''',(data[i][j],))
                            data_one = cursor.fetchall()
                            db.commit()
                            item = QtWidgets.QTableWidgetItem(data_one[0][1] + " " + data_one[0][2])
                            self.iss_table.setItem(i,j,item)
                        elif(j==2):
                            cursor.execute('''SELECT * FROM books WHERE id_book = ?''',(data[i][j],))
                            data_one = cursor.fetchall()
                            db.commit()
                            item = QtWidgets.QTableWidgetItem(data_one[0][1])
                            self.iss_table.setItem(i,j,item)
                        else:
                            item = QtWidgets.QTableWidgetItem(str(data[i][j]))
                            self.iss_table.setItem(i,j,item)                
                self.label_17.setText("Всего записей: " + str(row))
        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("sqlite3")
            msg.setInformativeText('Ошибка при работе с базой данных!')
            msg.setWindowTitle("Ошибка")
            msg.exec_()
    def f_iss_del_ok(self):
        try:           
            text = self.iss_del.text()
            data = cursor.execute('''SELECT * FROM issued WHERE id_iss = ?''',(text,))
            db.commit()
            if (data.fetchone() is None):
                msg=QMessageBox()
                msg.setText('Запись НЕ найдена!')
                msg.setWindowTitle(' ')
                msg.exec_()
            else:
                cursor.execute('''DELETE FROM issued WHERE id_iss = ?''',(text,))
                db.commit()
                msg=QMessageBox()
                msg.setText('Запись удалена!')
                msg.setWindowTitle(' ')
                msg.exec_()   
        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("sqlite3")
            msg.setInformativeText('Ошибка при работе с базой данных!')
            msg.setWindowTitle("Ошибка")
            msg.exec_()
    def f_iss_table_ref(self):
        try:
            cursor.execute('''SELECT * FROM issued''')
            data = cursor.fetchall()
            db.commit()
            if (len(data)!=0):    
                row = len(data)
                column = len(data[0])
                self.iss_table.setRowCount(row)
                for i in range(row):
                    for j in range(column):
                        if (j==1):
                            cursor.execute('''SELECT * FROM readers WHERE id_read = ?''',(data[i][j],))
                            data_one = cursor.fetchall()
                            db.commit()
                            item = QtWidgets.QTableWidgetItem(data_one[0][1] + " " + data_one[0][2])
                            self.iss_table.setItem(i,j,item)
                        elif(j==2):
                            cursor.execute('''SELECT * FROM books WHERE id_book = ?''',(data[i][j],))
                            data_one = cursor.fetchall()
                            db.commit()
                            item = QtWidgets.QTableWidgetItem(data_one[0][1])
                            self.iss_table.setItem(i,j,item)
                        else:
                            item = QtWidgets.QTableWidgetItem(str(data[i][j]))
                            self.iss_table.setItem(i,j,item)                
                self.label_17.setText("Всего записей: " + str(row))
            else:
                self.iss_table.setRowCount(0)
                self.label_17.setText("Всего записей: 0")

        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("sqlite3")
            msg.setInformativeText('Ошибка при работе с базой данных!')
            msg.setWindowTitle("Ошибка")
            msg.exec_()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Библиотека"))
        self.label_5.setText(_translate("Dialog", "Библиотека"))
        self.label_6.setText(_translate("Dialog", "Программа для работы с базой данных библиотеки."))
        self.label_7.setText(_translate("Dialog", "Записывайте выданные книги."))
        self.label_21.setText(_translate("Dialog", "Добавляйте новых читателей."))
        self.label_8.setText(_translate("Dialog", "Добавляйте новые книги."))
        self.label_22.setText(_translate("Dialog", "Курсовая работа Репина Максима"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Главная страница"))
        item = self.iss_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.iss_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Читатель"))
        item = self.iss_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Книга"))
        self.iss_table_ref.setText(_translate("Dialog", "Обновить таблицу"))
        self.label_17.setText(_translate("Dialog", "Всего записей: "))
        self.label_18.setText(_translate("Dialog", "Добавить запись"))
        self.iss_add_ok.setText(_translate("Dialog", "ОК"))
        self.label_19.setText(_translate("Dialog", "Найти запись"))
        self.iss_search_ok.setText(_translate("Dialog", "ОК"))
        self.label_20.setText(_translate("Dialog", "Удалить запись"))
        self.iss_del_ok.setText(_translate("Dialog", "ОК"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Dialog", "Выдача"))
        item = self.read_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.read_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Имя"))
        item = self.read_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Фамилия"))
        item = self.read_table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "E-mail"))
        self.read_table_ref.setText(_translate("Dialog", "Обновить таблицу"))
        self.label_16.setText(_translate("Dialog", "Всего записей: "))
        self.label_13.setText(_translate("Dialog", "Добавить читателя"))
        self.read_add_ok.setText(_translate("Dialog", "ОК"))
        self.label_14.setText(_translate("Dialog", "Найти читателя"))
        self.read_search_ok.setText(_translate("Dialog", "ОК"))
        self.label_15.setText(_translate("Dialog", "Удалить читателя"))
        self.read_del_ok.setText(_translate("Dialog", "ОК"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Читатели"))
        item = self.book_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.book_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Название"))
        item = self.book_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Автор"))
        item = self.book_table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Год"))
        self.book_table_ref.setText(_translate("Dialog", "Обновить таблицу"))
        self.label_9.setText(_translate("Dialog", "Всего записей: "))
        self.label_10.setText(_translate("Dialog", "Добавить книгу"))
        self.book_add_ok.setText(_translate("Dialog", "ОК"))
        self.label_11.setText(_translate("Dialog", "Найти книгу"))
        self.book_search_ok.setText(_translate("Dialog", "ОК"))
        self.label_12.setText(_translate("Dialog", "Удалить книгу"))
        self.book_del_ok.setText(_translate("Dialog", "ОК"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Книги"))
        item = self.auth_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.auth_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Имя"))
        item = self.auth_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Фамилия"))
        item = self.auth_table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Страна"))
        self.auth_table_ref.setText(_translate("Dialog", "Обновить таблицу"))
        self.label_4.setText(_translate("Dialog", "Всего записей: "))
        self.label.setText(_translate("Dialog", "Добавить автора"))
        self.auth_add_ok.setText(_translate("Dialog", "ОК"))
        self.label_3.setText(_translate("Dialog", "Найти автора"))
        self.auth_search_ok.setText(_translate("Dialog", "ОК"))
        self.label_2.setText(_translate("Dialog", "Удалить автора"))
        self.auth_del_ok.setText(_translate("Dialog", "ОК"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Авторы"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
